
from Filme.filme import Filme
filmes = []
filme1 = Filme("drive(2011)", "ação")
filmes.append(filme1)
filme2 = Filme("truque de mestre", "ação")
filmes.append(filme2)
filme3 = Filme("vingadores", "ação")
filmes.append(filme3)
filme4 = Filme("morbius", "ação")
filmes.append(filme4)
filme5 = Filme("trem-bala", "ação")
filmes.append(filme5)

filme6 = Filme("se beber nao case", "comédia")
filmes.append(filme6)
filme7 = Filme("minions", "comédia")
filmes.append(filme7)
filme8 = Filme("meu malvado favorito 2", "comédia")
filmes.append(filme8)
filme9 = Filme("luck", "comédia")
filmes.append(filme9)
filme10 = Filme("cidade perdida", "comédia")
filmes.append(filme10)

filme11 = Filme("jogos mortais", "terror")
filmes.append(filme11)
filme12 = Filme("a freira", "terror")
filmes.append(filme12)
filme13 = Filme("invocação do mal", "terror")
filmes.append(filme13)
filme14 = Filme("a avó", "terror")
filmes.append(filme14)
filme15 = Filme("tempo", "terror")
filmes.append(filme15)

filme16 = Filme("se7en", "suspense")
filmes.append(filme16)
filme17 = Filme("águas profundas", "suspense")
filmes.append(filme17)
filme18 = Filme("o telefone preto", "suspense")
filmes.append(filme18)
filme19 = Filme("a fera", "suspense")
filmes.append(filme19)
filme20 = Filme("você pertence a mim", "suspense")
filmes.append(filme20)

filme21 = Filme("interstellar", "ficção")
filmes.append(filme21)
filme22 = Filme("matrix", "ficção")
filmes.append(filme22)
filme23 = Filme("inception", "ficção")
filmes.append(filme23)
filme24 = Filme("a origem", "ficção")
filmes.append(filme24)
filme25 = Filme("perdido em marte", "ficção")
filmes.append(filme25)

filme26 = Filme("o melhor de mim", "romance")
filmes.append(filme26)
filme27 = Filme("diário de uma paixão", "romance")
filmes.append(filme27)
filme28 = Filme("365 dias", "romance")
filmes.append(filme28)
filme29 = Filme("através da minha janela", "romance")
filmes.append(filme29)
filme30 = Filme("espontânea", "romance")
filmes.append(filme30)