
from Filme.filme import Filme
filmes = []
arestas = []
listaGeneros = []
# Generos 
genero = Filme("genero", "genero")
listaGeneros.append(genero)
acao = Filme("acao", "acao")
listaGeneros.append(acao)
comedia = Filme("comedia", "comedia")
listaGeneros.append(comedia)
ficcao = Filme("ficcao", "ficcao")
listaGeneros.append(ficcao)
terror = Filme("terror", "terror")
listaGeneros.append(terror)
suspense = Filme("suspense", "suspense")
listaGeneros.append(suspense)
romance = Filme("romance", "romance")
listaGeneros.append(romance)


# Filmes
filme1 = Filme("drive(2011)", "acao")
filmes.append(filme1)
filme2 = Filme("truque de mestre", "acao")
filmes.append(filme2)
filme3 = Filme("vingadores", "acao")
filmes.append(filme3)
filme4 = Filme("morbius", "acao")
filmes.append(filme4)
filme5 = Filme("trem-bala", "acao")
filmes.append(filme5)

filme6 = Filme("se beber nao case", "comedia")
filmes.append(filme6)
filme7 = Filme("minions", "comedia")
filmes.append(filme7)
filme8 = Filme("meu malvado favorito 2", "comedia")
filmes.append(filme8)
filme9 = Filme("luck", "comedia")
filmes.append(filme9)
filme10 = Filme("cidade perdida", "comedia")
filmes.append(filme10)

filme11 = Filme("jogos mortais", "terror")
filmes.append(filme11)
filme12 = Filme("a freira", "terror")
filmes.append(filme12)
filme13 = Filme("invocacao do mal", "terror")
filmes.append(filme13)
filme14 = Filme("a avo", "terror")
filmes.append(filme14)
filme15 = Filme("tempo", "terror")
filmes.append(filme15)

filme16 = Filme("se7en", "suspense")
filmes.append(filme16)
filme17 = Filme("aguas profundas", "suspense")
filmes.append(filme17)
filme18 = Filme("o telefone preto", "suspense")
filmes.append(filme18)
filme19 = Filme("a fera", "suspense")
filmes.append(filme19)
filme20 = Filme("voce pertence a mim", "suspense")
filmes.append(filme20)

filme21 = Filme("interstellar", "ficcao")
filmes.append(filme21)
filme22 = Filme("matrix", "ficcao")
filmes.append(filme22)
filme23 = Filme("inception", "ficcao")
filmes.append(filme23)
filme24 = Filme("a origem", "ficcao")
filmes.append(filme24)
filme25 = Filme("perdido em marte", "ficcao")
filmes.append(filme25)

filme26 = Filme("o melhor de mim", "romance")
filmes.append(filme26)
filme27 = Filme("diario de uma paixao", "romance")
filmes.append(filme27)
filme28 = Filme("365 dias", "romance")
filmes.append(filme28)
filme29 = Filme("atraves da minha janela", "romance")
filmes.append(filme29)
filme30 = Filme("espontanea", "romance")
filmes.append(filme30)

